### ISSUE TITLE
Update Check Error

### ISSUE THREAD

**Issue by patrickhlauke** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#106]
This may already be resolved in the Beta 1.24, but: when I got the notification this morning in Beta 1.23 that the update was available, hitting "Download release" resulted in an error message:

> Could not find method named 'UncheckAll' on object of type 'NewVersionViewModel' that matches the expected signature

![Screenshot 2020-11-18 113231](https://user-images.githubusercontent.com/895831/99586997-5f1bc280-29e0-11eb-8e5c-0ee3e921efc2.png)

After dismissing the box, the scrubbler hung for a few seconds, then quit.

**Comment by SHOEGAZEssb** [comment]
Thanks for noticing, I fixed this now.
