### ISSUE TITLE
Can't parse Spotify JSON Files

### ISSUE THREAD

**Issue by lasselehmann** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#107]
It gives the error message "Error: TrackName can't be empty". I noticed that the name of the json files isn't StreamingHistory anymore, they are now called endsong_0 and so on. MAybe they changed the formatting inside the json file as well?

**Comment by SHOEGAZEssb** [comment]
Can you send an example of the json content?

**Comment by lasselehmann** [comment]
This is the date for one track:

{
    "ts": "2020-02-11T16:31:21Z",
    "username": "blockpasta",
    "platform": "Android OS 9 API 28 (HUAWEI, BND-L21)",
    "ms_played": 290736,
    "conn_country": "DE",
    "ip_addr_decrypted": "95.91.215.7",
    "user_agent_decrypted": "unknown",
    "master_metadata_track_name": "Carrion Flowers",
    "master_metadata_album_artist_name": "Chelsea Wolfe",
    "master_metadata_album_album_name": "Abyss",
    "episode_name": null,
    "episode_show_name": null,
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "skipped": null,
    "offline": false,
    "offline_timestamp": 1581438365846,
    "incognito_mode": false,
    "city": null,
    "region": null,
    "metro_code": null,
    "longitude": null,
    "latitude": null
  },

**Comment by SHOEGAZEssb** [comment]
Hmm it might be a good idea to make the name of the fields configurable..
For the time being you could convert the json to csv and use the CSV Scrobbler.

**Comment by 45O** [comment]
> Hmm it might be a good idea to make the name of the fields configurable..
> For the time being you could convert the json to csv and use the CSV Scrobbler.

Doesn't work, just shows this 
![Rven4K](https://user-images.githubusercontent.com/73535746/100830244-1a217280-345b-11eb-92cc-d2c7678612fa.png)

**Comment by SHOEGAZEssb** [comment]
> 
> 
> > Hmm it might be a good idea to make the name of the fields configurable..
> > For the time being you could convert the json to csv and use the CSV Scrobbler.
> 
> Doesn't work, just shows this
> ![Rven4K](https://user-images.githubusercontent.com/73535746/100830244-1a217280-345b-11eb-92cc-d2c7678612fa.png)

you need to configure your csv parser to use the correct index fields

**Comment by SHOEGAZEssb** [comment]
JSON parser can be configured with Scrubbler 1.25
