### ISSUE TITLE
How can the scrubbler read this file? Spotify sent me something weird.

### ISSUE THREAD

**Issue by McGrey02** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#109]
The Json-file looked not as it should usually do. I asked for my extended spotify history, but the Json-file gave me this below (I
blanked some private data with "_"):    

"ts": "2016-05-25T05:35:12Z",
    "username": "_",
    "platform": "_",
    "ms_played": 187541,
    "conn_country": "_",
    "ip_addr_decrypted": "_",
    "user_agent_decrypted": "unknown",
    "master_metadata_track_name": "Close",
    "master_metadata_album_artist_name": "IZECOLD",
    "master_metadata_album_album_name": "Close",
    "spotify_track_uri": "spotify:track:454IPfzFpYJsCvqbS0UDbR",
    "episode_name": null,
    "episode_show_name": null,
    "spotify_episode_uri": null,
    "reason_start": "appload",
    "reason_end": "trackdone",
    "shuffle": true,
    "skipped": null,
    "offline": false,
    "offline_timestamp": 0,
    "incognito_mode": false,
    "city": null,
    "region": null,
    "metro_code": 0,
    "longitude": 0,
    "latitude": 0

The normal scrubbler can't read this. Is there something I can do? Or do I have to change everything manually to trackName, etc.?

Thanks in advance

McGrey

**Comment by hans-juergen** [comment]
Did you choose the File Parser tab with file format JSON and click on the settings button after parsing? There should be a popup window to adapt to the used expressions in your file for artist, album, album artist and track.
