### ISSUE TITLE
Login failing to authenticate

### ISSUE THREAD

**Issue by lightsyoumake** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#110]
Hi, every time I try log in to last.fm in the Scrubbler, I get this error:

![image](https://user-images.githubusercontent.com/1949225/109667113-ec67d900-7bc3-11eb-9ee2-18602f1f1845.png)

**Comment by SHOEGAZEssb** [comment]
Which version are you on?
Can you login to the last.fm website with the same credentials?
Login works for me

**Comment by lightsyoumake** [comment]
I'm using version 1.17 and yes, I can log in using the same credentials. I double checked that before posting.

**Comment by SHOEGAZEssb** [comment]
That version is very outdated.
Please download the new one

**Comment by nonjenec** [comment]
@SHOEGAZEssb sorry for this. I have the same error as OP, using the latest 1.27 . it even locked my account after failing then tried testing if I could log in in browser.
