### ISSUE TITLE
Think Spotify just came out with a new code that the scrubbler cant read.

### ISSUE THREAD

**Issue by BoilingDust** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#111]
[Read_Me_First.pdf](https://github.com/SHOEGAZEssb/Last.fm-Scrubbler-WPF/files/6161671/Read_Me_First.pdf)

Idk if you can open that but its a document of showing how the new code for each played track works. The scrubbler version we have can't understand it.

**Comment by SHOEGAZEssb** [comment]
The current scrubbler version can already read this when you configure the JSON parser correctly

**Comment by BoilingDust** [comment]
> The current scrubbler version can already read this when you configure the JSON parser correctly

how does it work then? when i try to, it shows 0 were scrobbled, and there where 14562 errors

**Comment by BoilingDust** [comment]
![Screenshot (132)](https://user-images.githubusercontent.com/80876915/111652945-7a071380-87d5-11eb-91ed-c97a7356efe5.png)

**Comment by SHOEGAZEssb** [comment]
How do your json parser settings look like?

**Comment by BoilingDust** [comment]
![Screenshot (133)](https://user-images.githubusercontent.com/80876915/111657737-b89ecd00-87d9-11eb-850f-df763432ed08.png)

This? i just have defaults

**Comment by SHOEGAZEssb** [comment]
well yea that will not work because the properties are named differently in your json file

**Comment by BoilingDust** [comment]
so do i have to go one by one?

**Comment by BoilingDust** [comment]
Im not going through like 30k scrobbles one by one

**Comment by SHOEGAZEssb** [comment]
No just match your settings with the properties of your json

**Comment by BoilingDust** [comment]
oh so you mean putting the read me file parts?
"master_metadata_track_name": "_________,
“master_metadata_album_artist_name:_________”,
“master_metadata_album_album_name:_________",

**Comment by SHOEGAZEssb** [comment]
yup, just make sure you dont put any property name twice

**Comment by BoilingDust** [comment]
allright ill try it thanks

**Comment by BoilingDust** [comment]
so it seems to work fine but i got another problem haha, not with the scrubbler, but the file spotify gave me, it seems like the dates set are not in order going from 2020-08 to 2019-04 back up to 2020-06. I just dont want to rescrobble what i have. with the other format spotify gave out it was simple and all in order so i could just highlight all the plays from after i started lastfm and just delete. any way you know of how to do it with this new type of file?

**Comment by BoilingDust** [comment]
Never mind, if you just put ts in the time played section it adds date data when parsing, which allows you to filter by date to make sure no overlapping happens on my lastfm timeline. 
All problems fixed, thanks Shoegaze
