### ISSUE TITLE
Issue when importing CSV file with song datas containing commas ","

### ISSUE THREAD

**Issue by phokonte** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#112]
Hello, thanks for this software I find it very useful to import scrobbles from CSV file!
One of my friends had a problem, he lost his last.fm password and did not find any way to recover his account. So i wanted to transfer all his scrobbles from his old account to a new account.
Then i used Last.fm-Scrubbler-Wpf "_CSV Downloader_" to download all the scrobbles, so now I do have my CSV file containing all the scrobbles, but when I try to import it using "_File Parse Scrobbler_" i have an error saying that some scrobbles could not be parsed, i can then save a text file with the rows that could not be parsed, and I realise all the scrobbles which could not be parsed are the songs with datas containing commas "," in it because the _File Parse Scrobbler_ must have a problem when reading it, thinking it passes from Artist to Album for exemple, because each categories is supposed to be separated by commas.
So among 72,000 Scrobbles there are 3,000 songs that could not be parsed.

Here's an exemple of a line which could not be parsed:
_`CSV line number: 68910,M83,"Hurry Up,We're Dreaming",Midnight City,26/02/2019 08:34:33 +00:00,,,Timestamp could not be parsed!`_

Do you have any idea to fix this problem ?  This is not the first time I have encountered this problem, I regularly import scrobbles from a CSV file but it is often for fewer scrobbles, and it is then possible for me to set them manually, but 3,000 really seems like a lot. Perhaps there is something to be corrected in the import code of the CSV file? Or would I have a way to fix this problem myself?
Thank you very much!

**Comment by hans-juergen** [comment]
> One of my friends had a problem, he lost his last.fm password and did not find any way to recover his account.

He can contact the Last.fm support directly with their [email form](https://cbsi.secure.force.com/lastfm/submitcase_lfm?template=template_lastfm&referer=lastfm.com&cfs=LFM).

**Comment by SHOEGAZEssb** [comment]
The CSV parser has a setting "Contains fields enclosed in quotes", which should be checked if you have fields that contains ',' (these fields NEED to be enclosed in quotes)
