### ISSUE TITLE
iTunes Scrobbler does not scrobble album artist

### ISSUE THREAD

**Issue by kevinlim512** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#114]
iTunes scrobbler scrobbles current artist of song as album artist; e.g. "Ariana Grande & Doja Cat" instead of "Ariana Grande"

**Comment by SHOEGAZEssb** [comment]
Unfortunately no way around it - it works for some tracks, for others it doesn't.
It's a bug in the COM interop :(
