### ISSUE TITLE
Can't select the artist, album or track and edit it all at once!

### ISSUE THREAD

**Issue by etfromhere** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#115]
I would like to know if there is any way I can select more than just one file and edit its name, album or track at once.
For example, select all those files with the wrong name and edit them to Eve.

![image](https://user-images.githubusercontent.com/86111915/122563468-a0c62780-d01a-11eb-90fd-4d5007052279.png)

**Comment by SHOEGAZEssb** [comment]
That honestly looks like you configured your csv scrobbler wrong.
The field indexes should match your data indexes in the csv
