### ISSUE TITLE
Error connecting to iTunes

### ISSUE THREAD

**Issue by vincegiordano** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#123]
![image](https://user-images.githubusercontent.com/26976101/149579422-fc9a586e-322e-4005-8567-4a234ba0ff08.png)

**Comment by SHOEGAZEssb** [comment]
Please have a look at this issue: https://github.com/SHOEGAZEssb/Last.fm-Scrubbler-WPF/issues/46
