### ISSUE TITLE
Scrobble older than x days?

### ISSUE THREAD

**Issue by Offerel** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#124]
I will switch over my old library to a new library application. In the old application i can export a list of all the played songs including last played timestamp and playcount to a csv file. A lot of these timestamps are older than 1 year. I have tried to manually scrobble a song to last.fm. This works for the current timestamp, but not for timestamps older then x days. So i wonder, if there is a limit how old such a scrobble could be.

Is this the case? How far back in time can i scrobble a song? Is there some way to raise this limit to 1 year back or older?

**Comment by SHOEGAZEssb** [comment]
The limit is 14 days and no unfortunately there is no way to go around this limit
