### ISSUE TITLE
Add UTF-8 BOM to exported CSV

### ISSUE THREAD

**Issue by rzumer** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#125]
This is just a suggestion to add the byte-order mark to the CSV output, because when reading it in something like Excel that does not default to UTF-8, or when trying to parse it back in the File Parse Scrobbler tab, the wrong character encoding or byte order is assumed and non-ASCII characters are not parsed properly, generating errors in some cases.

After adding a BOM to the CSV output through Notepad++, everything was parsed normally and the list of tracks looks good, so I think that should be added by default (or alternatively use a different default encoding for file parsing if there isn't enough universal support for UTF-8 with BOM).

**Comment by SHOEGAZEssb** [comment]
Fixed in 1.30
