### ISSUE TITLE
Error while scrobbling selected tracks: Cached

### ISSUE THREAD

**Issue by hypnaceae** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#127]
Scrobbling from CSV, which can be found here: https://www.klgrth.io/paste/8ohb4
Parser settings: UTF-8, "Has Fields Enclosed in Quotes" checked.

Can't find said cache anywhere, so like this I have no idea what went wrong to try and troubleshoot.

**Comment by straykds** [comment]
yeah, it also happens to me all the time. i think the scrobbler doesn't allow 3000 tracks per day, it's more like 2000 or less.

**Comment by UserNo84** [comment]
I'm having the same problem when using the friend scrobbler. According to the app, I've only used 37 out 3000 daily scrobbles. Could the dev of this tool please respond? This topic was opened six months ago. Thanks.

**Comment by SHOEGAZEssb** [comment]
Sorry this seems to be an issue on last.fms side. Please just wait a few hours and try again

**Comment by szalovszky** [comment]
Currently having the same issue.
Was it a last.fm issue or is there something broken client-side?

**Comment by SHOEGAZEssb** [comment]
I still do not know what exactly causes this issue, but it seems to resolve itself after waiting a bit
