### ISSUE TITLE
Track and album swapped and other errors

### ISSUE THREAD

**Issue by LeanderAT** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#128]
Hello!

I downloaded the .csv of my three accounts. Then I uploaded them to a new profile with Scrubbler. ..using File Parser.

Sometimes track and album are swapped. A track is stored as an album and vice versa... e.g. the track "Example" is stored as a new album of a band...although it is a song.

Moreover, if a song shares the name with the album it is on, playing other songs on the album count towards the song of the same name.

Example:

Band: Band
Album: Super Rock
Songs:
1) Intro
2) Super Rock
3) Hell yeah
4) Let's do this
5) Final swing

Playing "Hell yeah" on the album "Super Rock" counts towards the SONG "Super Rock"...so if you listen to the entire album, Intro, Heall yeah, Let's do this and final swing have counts of 1 scrobbles but "Super Rock" has 5...because the album is entitled "Super Rock" as well and every song on that album counts towards the song "Super Rock".

Another question: What does Scrubbler need in order to work?

Example:

Band,Album,Track,31.01.2018 04:58:59 +00:00,,

Is this correct? Does the time format need to be in US order, month, day, year? Or is day, month, year ok? What about the "+00:00,," at the end?

When using File Parser all songs were stored to be scrobbled in 2022...on the actual day of uploading the file.

How can I keep the real date so a song played in 2008 is correctly stored? I don't want to have thousands of songs in 2022 when combining accounts.

**Comment by SHOEGAZEssb** [comment]
First off, always make sure your csv is parsed in the correct order. Different CSV files come in different orders and that needs to be configured. You can configure the csv parser via the "Settings" button next to the csv dropdown in the file parser.
Secondly, the timestamps will be mainly ignored since last.fm does not allow scrobbles older than 14 days, therefore your scrobbles will always look like they have been scrobbled in 2022.

**Comment by LeanderAT** [comment]
Thank you!

**Comment by LeanderAT** [comment]
PS How should .csv files be saved? I downloaded them with https://benjaminbenben.com/lastfm-to-csv/

1) After editing should I save it in .csv (separated by separator) or .csv UTF8 (separated by separator)? Before I upload such files with Scrubbler?

2) What do I have to edit in the file? Special characters (e.g. German ones) are displayed incorrectly.
"Empyrium,Ãœber den Sternen (Luxus),Ãœber den Sternen,28 Nov 2021 00:10"

"Ãœber den Sternen" should be "Über den Sternen"...should I replace such characters in all files or keep them as Last.fm will display them correctly after uploading the file with Scrubbler?

3) Do all entries require an album? Sometimes it is band,,track,time stamp... without an album.

**Comment by SHOEGAZEssb** [comment]
Album is optional. You can also configure the encoding of the parsing process in the settings. Since I do not know which one your specific file needs you can just try around until one of them fits.

**Comment by LeanderAT** [comment]
Thanks! And the special characters? I will fix thousands of entries manually so want to make sure everything is correct before uploading. :)

**Comment by SHOEGAZEssb** [comment]
Special characters should be parsed correctly, when you have the correct encoding selected

**Comment by LeanderAT** [comment]
What encoding should be selected? Just saw you are German. Soll ich "CSV Trennzeichen getrennt" wählen oder "CSV UFT8 Trennzeichen getrennt"? Excel fragt mich beim Speichern von Änderungen genau...einfach speichern geht nicht.

**Comment by SHOEGAZEssb** [comment]
You have to change the encoding IN the Scrubbler, I dont think the encoding you choose in excel really matters that much

**Comment by LeanderAT** [comment]
Thanks! I replaced the characters in Excel and tested it with the corrupted account...it works. :)  Fixing everything (especially Alcest's French characters) takes a while but finally, Last.fm finds the correct songs.

**Comment by LeanderAT** [comment]
Ich habe ein neues Profil begonnen. Von 2800 Scrobbles waren 2785 erfolgreich. Von Adversus fehlen 10 Scrobbles, von Adrima 1, von Algazanth 4. Hab aber keine Ahnung, wo der Fehler ist? Bei Adversus wurde "Seelenwinter" nur 1x gescrobbelt, "Zimmer im Kopf" auch nur 1x.

Adversus,Winter so unsagbar Winter...,Berühr' mich nicht,23 Aug 2014 02:56
Adversus,Winter so unsagbar Winter...,Berühr' mich nicht,30 Mar 2014 04:17
Adversus,Winter so unsagbar Winter...,Klingentanz,03 Feb 2020 18:46
Adversus,Winter so unsagbar Winter...,Klingentanz,03 Oct 2016 15:49
Adversus,Winter so unsagbar Winter...,Klingentanz,06 Dec 2018 20:05
Adversus,Winter so unsagbar Winter...,Klingentanz,10 Jul 2015 03:04
Adversus,Winter so unsagbar Winter...,Klingentanz,13 May 2020 19:01
Adversus,Winter so unsagbar Winter...,Klingentanz,20 Dec 2016 20:20
Adversus,Winter so unsagbar Winter...,Klingentanz,23 Aug 2014 02:49
Adversus,Winter so unsagbar Winter...,Klingentanz,30 Mar 2014 04:11
Adversus,Winter so unsagbar Winter...,Seelenwinter,03 Feb 2020 18:53
Adversus,Winter so unsagbar Winter...,Seelenwinter,06 Dec 2018 20:11
Adversus,Winter so unsagbar Winter...,Seelenwinter,10 Jul 2015 04:11
Adversus,Winter so unsagbar Winter...,Seelenwinter,13 May 2020 19:07
Adversus,Winter so unsagbar Winter...,Seelenwinter,23 Aug 2014 03:02
Adversus,Winter so unsagbar Winter...,Seelenwinter,30 Mar 2014 04:23
Adversus,Winter so unsagbar Winter...,Zimmer im Kopf,03 Oct 2016 15:47
Adversus,Winter so unsagbar Winter...,Zimmer im Kopf,20 Dec 2016 20:18
Adversus,Winter so unsagbar Winter...,Zimmer im Kopf,28 Jul 2015 19:04
Adversus,Winter so unsagbar Winter...,Zimmer im Kopf,30 Mar 2014 04:09
Adversus,Winter so unsagbar Winter…,Seelenwinter,05 Oct 2013 00:09
Adversus,Winter so unsagbar Winter…,Zimmer im Kopf,05 Oct 2013 00:16

===========

Adrima,,I Can't Stop Raving 2001 [Club Mix],22 Aug 2008 22:28
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 (Club Mix),03 Jul 2017 09:54
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 (Club Mix),05 Feb 2012 04:22
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 (Club Mix),17 May 2017 13:52
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 (Club Mix),19 Jun 2017 17:46
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 (Club Mix),19 Sep 2011 22:15
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 (Club Mix),20 Aug 2014 05:41
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 (Club Mix),20 Jan 2014 14:14
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 (Club Mix),20 Jul 2013 03:27
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 (Club Mix),23 Jul 2016 02:00
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 [Club Mix],12 Apr 2009 23:43
Adrima,Hardcore Flashback III,I Can't Stop Raving 2001 [Club Mix],27 May 2009 14:39

===========

Alghazanth,,Daemonolith,20 Jan 2006 02:14
Alghazanth,,Ensnared in Moonshades,20 Jan 2006 02:20
Alghazanth,,Regained Planetary Possession,04 May 2006 16:54
Alghazanth,,Regained Planetary Possession,20 Jan 2006 02:24
Alghazanth,,Regained Planetary Possession,25 Aug 2005 01:12
Alghazanth,,the circle of six,04 May 2006 16:58
Alghazanth,,the circle of six,20 Jan 2006 02:32
Alghazanth,,The Thorns Cry Blood,20 Jan 2006 02:06
Alghazanth,,The Thorns Cry Blood,20 Jan 2006 02:48
Alghazanth,Subliminal Antenora,Daemonolith,04 May 2006 16:44
Alghazanth,The Polarity Axiom,Soulquake,20 Jan 2006 02:09
Alghazanth,Thy Aeons Envenomed Sanity,Ensnared in Moonshades,04 May 2006 16:49
Alghazanth,Thy Aeons Envenomed Sanity,The Thorns Cry Blood,04 May 2006 16:40
