### ISSUE TITLE
issue while trying to scrobble tracks with parentheses

### ISSUE THREAD

**Issue by straykds** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#130]
everytime i try to scrobble a track on file parse (csv) with () it make the track go to the other side. i tried to change the encoding on settings but nothing helps.

![cats](https://user-images.githubusercontent.com/76923371/194728327-0e3fd642-2214-43d3-b3c7-4c4fb2e60f17.jpg)

**Comment by SHOEGAZEssb** [comment]
how do these entries look in the csv file?

**Comment by straykds** [comment]
> how do these entries look in the csv file?


like this ! 

![cats](https://user-images.githubusercontent.com/76923371/194766089-871bb151-63b1-4e5e-afa1-f6113bc35ad9.jpg)

**Comment by SHOEGAZEssb** [comment]
Yeah, its because of the ',' inside the paranthesis.
Thats just something with csv.
You will need to put these fields inside quotes ("")
