### ISSUE TITLE
iPod plays not detected

### ISSUE THREAD

**Issue by theSplund** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#131]
I use ListenBrainz mainly (using SimpleScrobbler from my Android), but I can update my ListenBrainz data from my lastFM account. This Scrubbler project works well to get my 'now playing' iTunes/PC scrobbles into lastFM, however the Scrubbler doesn't seem to detect/upload any plays that happened on my iPod when I plug it in and sync - is this a known limitation? Thanks

**Comment by SHOEGAZEssb** [comment]
Yes this is a known limitation. Tried to implement it a few times but its very hard and not worth the effort unfortunately
