### ISSUE TITLE
Plans to make scrubbler compatible with Apple Music on Win 11?

### ISSUE THREAD

**Issue by patrickhlauke** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#135]
It's probably way too early to say, but: before I give this a try, are there plans (and/or is it even possible, depending on how they've coded it) to make scrubbler compatible with the upcoming Apple Music app https://apps.microsoft.com/store/detail/apple-music-preview/9PFHDD62MXS1?ranMID=24542&ranEAID=TnL5HPStwNw&ranSiteID=TnL5HPStwNw-_Z00eHonZroBU4dvLLfH1w&epi=TnL5HPStwNw-_Z00eHonZroBU4dvLLfH1w&irgwc=1&OCID=AID2200057_aff_7593_1243925&tduid=%28ir__kwqbb2wum0kfbhayinyi6ijhrn2xcpngdhn0u2xk00%29%287593%29%281243925%29%28TnL5HPStwNw-_Z00eHonZroBU4dvLLfH1w%29%28%29&irclickid=_kwqbb2wum0kfbhayinyi6ijhrn2xcpngdhn0u2xk00 ?

**Comment by SHOEGAZEssb** [comment]
I havent had a look at it yet, but seems interesting.
I can't say how doable it is without having a look, and knowing Apple there won't be any interface I can easily access, but we'll see

**Comment by cillyk** [comment]
I worry it will be challenging. does not seem to act like a normal media player, like it doesn't even use media keys or show any now playing info anywhere.

**Comment by patrickhlauke** [comment]
it may just be because it's currently only a preview build...i'd hope that for the final version, they'll hook into more properly to the Win 11 system itself and expose things through the appropriate APIs (or maybe i'm just too optimistic, knowing how Apple operate sometimes...)

**Comment by Lucas11925** [comment]
any plans on add that on your next update?

**Comment by DnlMcn** [comment]
I would really, **really** appreciate it if this was added. The legacy iTunes program feels really decrepit right now, and recently the performance has only gotten worse, like it's falling apart. I tried Cider (the third-party app) and it looks good visually but it doesn't have many of the functionalities I need. This new Apple Music app looks like the best option. 

Also, I'm just guessing here, but based on the fact that they can't coexist on your machine (the old iTunes doesn't work for music if you have this one installed), I imagine they could be very similar in the back-end. It mostly looks like a reskin of iTunes, plus some additions and polish. Even the settings options are the same. So it would be awesome if you could check it out and possibly add compatibility with it, since I think they could turn out to be similar.

**Comment by patrickhlauke** [comment]
I hadn't actually clocked that Apple Music was now out of beta ... and as iTunes was slowly but surely falling apart (struggling to even scroll through my vast music collection), I took the stable release for a spin ... not realising that doing so pretty much disabled iTunes, oops. So at the moment, looks like I won't be able to use the Scrubbler here, which is unfortunate as I really came to rely on its "set it and forget it" usefulness. Hoping that there will be a way to somehow hook it into Music (the approach there taken by AMWin-RP looks outrageously hacky and flaky...wonder if there's a cleaner/more fundamental way (some form of "this audio source is currently playing X" type API in Windows) that can be hooked into...

**Comment by DnlMcn** [comment]
yeah well that's the problem, from what I can tell, iTunes was already bad in regards to exposing media playback information, and it seems that the new Apple Music app is even more so. Not only that, there aren't any libraries or API's for that yet. So, at least for now, AMWin-RP's way of doing it is the only known way of doing it.

and tbh, I don't really mind a hacky solution. as long as AM's interface works, so will AMWin-RP, and I'm fine with that.

**Comment by SHOEGAZEssb** [comment]
I'm still thinking about implementing this at some point, I just don't have a lot of time currently

**Comment by hans-juergen** [comment]
You might want to check out the new Music Presence Discord app which already supports Apple Music, even the Windows version, as far as I know:

https://github.com/ungive/discord-music-presence

The difference to AMWin-RP is that it also supports many local media players and streaming sites. The developer is currently preparing to add an internal scrobbling option, too.

**Comment by DnlMcn** [comment]
Seems interesting! Though scrobbling is the most important feature for me, above even rich presence, I'll definitely keep this on my radar

**Comment by SHOEGAZEssb** [comment]
added in 1.33

**Comment by patrickhlauke** [comment]
whoah, amazing. i'll need to take it for a spin again (felt like cheating the last few months, running AMWin-RP)
