### ISSUE TITLE
File Parse JSON Scrobbler not scrobbling the date the song played.

### ISSUE THREAD

**Issue by squisan** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#136]
I'm uploading my spotify listening history to last fm, but it seems that Last.fm Scrubbler doesn't detect the time the song played as stated in the JSON file

example: 
```
 "artistName": "Omori",
    "albumName": "Omori (Original Game Soundtrack), Pt.1",
    "trackName": "Trouble - Never/Always",
    "time": "2022-01-06T00:32:16Z"
```

Everything else there it detects fine, artist name, album name, song title, but it doesn't detect the time played... it just keeps trying to scrobble at the current time. Is this intentional?

![image](https://github.com/SHOEGAZEssb/Last.fm-Scrubbler-WPF/assets/128754753/7f1a9fe5-b0c6-4689-a45f-3194271d0063)

![Screenshot_55](https://github.com/SHOEGAZEssb/Last.fm-Scrubbler-WPF/assets/128754753/07253e0e-8674-4e59-a8bc-76e6d1060fe4)

**Comment by SHOEGAZEssb** [comment]
This is intentional, since last.fm does not allow scrobbles older than 2 weeks
