### ISSUE TITLE
Failed to Login or Authenticate

### ISSUE THREAD

**Issue by schwa24** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#137]
I'm not able to log in despite having login credentials that work elsewhere, ive tried resetting the password and running the program with elevated permissions.

**Comment by ironavt** [comment]
I have the same issue. It appears, the reason is Last.fm does not allow logging in via third-party apps using username and password explicitly

**Comment by sepl2604** [comment]
Yep, same issue. Is there a workaround? What are all the other users doing, which already added their account? Is app still working for them?

cheers!

**Comment by ironavt** [comment]
I just found out there is v 1.27 here https://github.com/SHOEGAZEssb/Last.fm-Scrubbler-WPF/releases 
Authentication worked for me in this one
