### ISSUE TITLE
Minor: Track/Artist/Album links in iTunes Scrobbler show last played piece but don't work

### ISSUE THREAD

**Issue by patrickhlauke** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#138]
More like a minor nitpick than a hard bug, but: if you listen to something in iTunes, and it then finishes playing (and nothing more is playing), the iTunes Scrobbler still shows the last Track/Artist/Album - but the links are empty/broken (following them goes to `https://www.last.fm/music//`)

![screenshot of the iTunes Scrobbler, showing the last known good track that was played with visible links](https://github.com/SHOEGAZEssb/Last.fm-Scrubbler-WPF/assets/895831/a91afa66-d026-4a28-8788-d0fe24d767c6)

I guess there's two ways to go about this:

* blank out the track/artists/album once playback finished and there's nothing more playing
* store the values / urls for those links, so when clicking them it still goes to the correct destination

**Comment by SHOEGAZEssb** [comment]
Fixed with 1.28

**Comment by patrickhlauke** [comment]
Magic, thank you
