### ISSUE TITLE
Error while scrobbling: Cached

### ISSUE THREAD

**Issue by BotJohn** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#143]
Hello,
I've been able to scrobble fine over the past week, but started getting this issue today.
About 2630-2780 out of 2850 tracks scrobbled fine, and since then I have been having this issue even when trying to scrobble a single track.

**Comment by SHOEGAZEssb** [comment]
It means you are getting scrobble limited -> Wait 24 hours then try again, there is nothing else you (or I) can do unfortunately
