### ISSUE TITLE
"Successfully parsed file. Parsed 0 Scrobbles" when trying to upload JSON of historical scrobbles. 

### ISSUE THREAD

**Issue by steaming-mangos** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#149]
I have a prepared json with this format:

```
[
    {
        "artistName": "Spoon",
        "albumName": "Can I Sit Next to You",
        "trackName": "Can I Sit Next to You",
        "time": "2018-01-30T06:19:18Z"
    },
    {
        "artistName": "Ween",
        "albumName": "The Mollusk",
        "trackName": "Ocean Man",
        "time": "2018-01-30T06:21:25Z"
    },
    {
        "artistName": "Destroyer",
        "albumName": "Destroyer's Rubies",
        "trackName": "Painter in Your Pocket",
        "time": "2018-01-30T06:21:59Z"
    }
]
```
When I try to upload it, it says "Successfully parsed file. Parsed 0 scrobbles"

**Comment by steaming-mangos** [comment]
The issue was with the settings (the button located next to where you select the parser). I had to change the field properties to match the JSON file.

**Comment by Crxaw** [comment]
> The issue was with the settings (the button located next to where you select the parser). I had to change the field properties to match the JSON file.

By any chance can I have the field properties you used for this? Since I have the same format with no result.
