### ISSUE TITLE
Error while scrobbling selected tracks: Cached

### ISSUE THREAD

**Issue by wmsalves** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#150]
I'm trying to scrobble from another account but the following error is being generated.

Error while scrobbling selected tracks: Cached.

I tried selecting just a few songs, changing the default duration per song but the error is still generated.

**Comment by SHOEGAZEssb** [comment]
The cached error usually means that last.fm is limiting the amount of scrobbles you can submit. Maybe you reached the limit? You can try again later.
