### ISSUE TITLE
Error message when starting

### ISSUE THREAD

**Issue by hans-juergen** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#152]
I get this error message now when starting the app (version 1.31 and 1.32):
![image](https://github.com/user-attachments/assets/1d9f04ec-22eb-4a31-9d61-b45ee8b71f2a)
So it seems to be caused by the automatic update check, but it does not prevent starting it when I click on OK.

**Comment by GaabluhnMowd** [comment]
Also getting same error on startup.

**Comment by SHOEGAZEssb** [comment]
Should be fixed, was an issue with the tag name of the current release

**Comment by hans-juergen** [comment]
Yep, no error anymore when starting current 1.32 version as admin. By the way, is there any option to force starting as admin each time other than manually opening the extended properties of the start menu link? I always seem to forget where exactly I have to set the checkmark. 😉
![image](https://github.com/user-attachments/assets/42f9597c-8459-4cc0-a6dd-bc6bd8303fbe)

**Comment by SHOEGAZEssb** [comment]
> Yep, no error anymore when starting current 1.32 version as admin. By the way, is there any option to force starting as admin each time other than manually opening the extended properties of the start menu link? I always seem to forget where exactly I have to set the checkmark. 😉 ![image](https://private-user-images.githubusercontent.com/4970867/389901125-42f9597c-8459-4cc0-a6dd-bc6bd8303fbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NTYwNzMsIm5iZiI6MTczMjY1NTc3MywicGF0aCI6Ii80OTcwODY3LzM4OTkwMTEyNS00MmY5NTk3Yy04NDU5LTRjYzAtYTZkZC1iYzZiZDgzMDNmYmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMjExNjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTE4NzY2NGUzMDQzOWRjZmFiYWNkZmNiNzhiOWFkNDIxYjU3YTkzNjA4NTMwNjBmNGU4N2EyNmFjNmVmODdhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FqR0-LigpWHaL21_dnidxBMOiqH3ge7ApJ_y2OlEubg)

I could do that, but what do you need admin rights for?

**Comment by hans-juergen** [comment]
I'm on Windows 10 Pro 64-bit, Build 19045.5198, and I have to start Scrubbler with admin rights each time, otherwise it will be blocked by Windows.

![image](https://github.com/user-attachments/assets/8d4ceb31-0967-465d-a593-110c3bf53f18)

This has always been the case for me, also with older versions.

**Comment by GaabluhnMowd** [comment]
Just chiming in - I'm able to run the program just fine without admin privileges on both Windows 10 and Windows 11, so I think this is specific to your setup.

**Comment by SHOEGAZEssb** [comment]
Yeah, thats what I was thinking too. Never had any issues or reports regarding admin rights with the Scrubbler.
Introducing it might cause more trouble than it would fix

**Comment by hans-juergen** [comment]
OK, it probably happens, because I install Scrubbler in a subdirectory of the Last.fm program folder in Windows which affords admin rights as well:

![image](https://github.com/user-attachments/assets/53a4c84c-21c7-4d1c-8c6c-b7a9f1909674)
