### ISSUE TITLE
Current Status: Error while scrobbling selected tracks: Cached

### ISSUE THREAD

**Issue by S2shapedbox** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#153]
Hello! Started using scrubbler yesterday and ran into this issue. I tried selecting about 2900 tracks at once, and it worked perfectly, but every time after that, it displays the title error.

**Comment by SHOEGAZEssb** [comment]
https://github.com/SHOEGAZEssb/Last.fm-Scrubbler-WPF/issues/143
