### ISSUE TITLE
JSON file parse scrobbler: special characters handled incorrectly

### ISSUE THREAD

**Issue by jonas-resch** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#154]
Hi,

I exported my listening history from Spotify. When using the file parse scrobbler tracks with special characters in the title or artist name won't get scrobbled. There also is no feedback that a scrobble failed.

E.g. "Tiësto - Red Lights" won't get scrobbled due to the "ë" in the artist name. Same as for some Spanish characters and German umlauts (ä, ö, ü).

The name is correct in the JSON file (see attachment).

If someone can point me to the code where the JSON parsing is done I will try to fix it myself and create a PR.

[red-lights.json](https://github.com/user-attachments/files/18221541/red-lights.json)

![special-characters](https://github.com/user-attachments/assets/1ac7a395-7b9c-4b95-b51b-529458c1028a)

**Comment by SHOEGAZEssb** [comment]
![grafik](https://github.com/user-attachments/assets/fe7da9c4-c0e2-4f2e-8399-b5033ce81f16)

I can not reproduce this issue.
It might have something to do with your OS language (mine is German)

**Comment by jonas-resch** [comment]
Hi,
thanks for the quick reply! I found the issue: the JSON splitter saves files with ANSI and not UTF-8 encoding. Once I converted the JSON files to UTF-8 manually, special characters were read correctly.

**Comment by SHOEGAZEssb** [comment]
ah goddamnit that shit again. thanks for noticing, I'll fix it

**Comment by jonas-resch** [comment]
Thanks a lot! :)

**Comment by SHOEGAZEssb** [comment]
fixed in 1.33

**Comment by jonas-resch** [comment]
Damn, that was fast. Thanks!
