### ISSUE TITLE
CSV import and track duration

### ISSUE THREAD

**Issue by lowresoluti0n** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#77]
When I import some tracks in a CSV file with the "Import mode", I would like that the duration of the tracks was taken from the CSV file, instead of having to use a default duration that is the same for every track.
I am aware that if I use the "Normal mode" I can specify the duration for each track, but I find "Import mode" much more convenient because I don't have to provide a timestamp. Would it be possible for the program to calculate the correct finishing time for each track while having as an input the finishing time of the top selected/last track and the duration of every track?

P.S. Thank you for your efforts in providing this handy scrobbling alternative

**Comment by SHOEGAZEssb** [comment]
I will close this now, since last.fm ignores duration anyways
