### ISSUE TITLE
Album artist tagging is not possible for Friend Scrobble section

### ISSUE THREAD

**Issue by pawgal** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#84]
Album artist is not visible for Friend Scrobble section. Artist Album can't be edited before subbmitting.

**Comment by coczero** [comment]
Thats because the last.fm api does not return the AlbumArtist when getting scrobbles.
I could theoretically add the AlbumArtist row so people could add the info themselves, but I'm not sure how useful that would be.

**Comment by pawgal** [comment]
This could be useful for editing artist album which should be corrected. For example: user listened album with (Deluxe) or (Remastered) info that should be deleted before submitting

**Comment by pawgal** [comment]
When you use user.getRecentTracks method there's an information what album was used to scrobble.

Example Below:

http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=pawgal&api_key=API_KEY

`<?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
   <recenttracks user="pawgal" page="1" perPage="50" totalPages="4646" total="232281">
      <track>
         <artist mbid="d7a18d20-8591-43af-b8e7-362eacc979f8">Arkona</artist>
         <name>Vozrozhdenie</name>
         <streamable>0</streamable>
         <mbid />
         <album mbid="b5c8486a-42b0-401a-adcd-f69f0074d597">Vozrozhdenie</album>
         <url>https://www.last.fm/music/Arkona/_/Vozrozhdenie</url>
         <image size="small">https://lastfm-img2.akamaized.net/i/u/34s/000e7ed7fe3d246cb1390144c67dbc60.jpg</image>
         <image size="medium">https://lastfm-img2.akamaized.net/i/u/64s/000e7ed7fe3d246cb1390144c67dbc60.jpg</image>
         <image size="large">https://lastfm-img2.akamaized.net/i/u/174s/000e7ed7fe3d246cb1390144c67dbc60.jpg</image>
         <image size="extralarge">https://lastfm-img2.akamaized.net/i/u/300x300/000e7ed7fe3d246cb1390144c67dbc60.jpg</image>
         <date uts="1565085777">06 Aug 2019, 10:02</date>
      </track>
   </recenttracks>
</lfm>
...
`
so <album mbid="b5c8486a-42b0-401a-adcd-f69f0074d597">Vozrozhdenie</album> could be added to the app and if user want - to correct it. Sometimes mbid ="", but album artist is visible.

**Comment by coczero** [comment]
The problem isnt the Album info its the AlbumArtist info.
I currently don't plan on adding additional acquiring of information (for example checking the albumartist via the album mbid)
