### ISSUE TITLE
Tracks duration is not get from lastfm / musicbrainz release 

### ISSUE THREAD

**Issue by pawgal** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#85]
Every track loaded from lastfm DB or musicbrainz has no duration added. Date time for submiting scrobbles could be calculated based on lastfm DB or musicbrainz. User could have choice to set default duration time (ie. 3 minutes) or use loaded duration track.

**Comment by SHOEGAZEssb** [comment]
Duration is ignored by last.fm by now
