### ISSUE TITLE
Feature Request: Oauth for login

### ISSUE THREAD

**Issue by andrewc2** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#91]
It would be great for it to be able to use Oauth login like the official scrobbler does. User/Pass auth is pretty insecure especially when you don't know how an app is using it.

**Comment by coczero** [comment]
I agree, I'd like to use Oauth too, but the last.fm library I use currently does not yet support it.

**Comment by SHOEGAZEssb** [comment]
Implemented with Beta 1.29
