### ISSUE TITLE
Scrubbler won't scrobble if you go 2 weeks before

### ISSUE THREAD

**Issue by ManuMillenaar** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#98]
If you select 2 weeks before the current date, and the hour is before the current one (shouldn't let you do that?) it'll say you scrobbled (an add for the 2800 cap) but won't show in last.fm.

**Comment by kachan64** [comment]
I don't think Last.FM allows anything to be scrobbled before the 2 weeks time period and that how they set.
How did you do it? I export my Winamp database, imported through the app na checked all then hit scrobble.
Once was done. I checked Last.FM and was showing everything as 14 min ago or something and just piled up on top of my existing scrobble.

**Comment by MeinStyle** [comment]
You can select date to scrobble (within the 2 weeks period), but if you select especifically 2 weeks before and a time before the current one, it won't scrobble (cause you can't of course) but it won't show error and looks as if you have scrobbled correctly (and also add to the 2800 day cap and don't let you scrobble more that day).

Just a minor bug.

**Comment by kakyoins** [comment]
i set the date to 2013 and the whole app crashed lol

**Comment by Kell0ee** [comment]
I seem to have just had the same issue. Set the date to 2 weeks before (21st Dec) and left the time as it was. Doesnt seem to be appearing in Last.fm 
Set it to 13 days before and its worked fine :)
